builds:
  - binary: saw
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    env:
      - CGO_ENANBLED=0

archive:
  format: tar.gz
  files:
    - LICENSE

brew:
  name: saw

  github:
    owner: logandavies181
    name: homebrew-slaw

  commit_author:
    name: logandavies181
    email: logan.davies181@gmail.com

  folder: Formula
  homepage: "https://github.com/logandavies181/slaw"
  description: "Fast, multipurpose tool for AWS CloudWatch Logs"

git:
  short_hash: true

nfpm:
  vendor: Logan Davies
  homepage: https://github.com/logandavies181/slaw
  maintainer: Logan Davies <logan.davies181@gmail.com>
  description: Fast, multipurpose tool for AWS CloudWatch Logs
  license: MIT
  formats:
    - deb
    - rpm
